<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Padukuhan;

class PadukuhanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // KAPANEWON BAMBANGLIPURO
            // Mulyodadi (id=1)
            ['nama' => 'Bregan', 'kelurahan_id' => 1],
            ['nama' => 'Cangkring', 'kelurahan_id' => 1],
            ['nama' => 'Carikan', 'kelurahan_id' => 1],
            ['nama' => 'Destan', 'kelurahan_id' => 1],
            ['nama' => 'Jomblang', 'kelurahan_id' => 1],
            ['nama' => 'Kepuh', 'kelurahan_id' => 1],
            ['nama' => 'Kraton', 'kelurahan_id' => 1],
            ['nama' => 'Mejing', 'kelurahan_id' => 1],
            ['nama' => 'Ngambah', 'kelurahan_id' => 1],
            ['nama' => 'Paker', 'kelurahan_id' => 1],
            ['nama' => 'Plumutan', 'kelurahan_id' => 1],
            ['nama' => 'Tulasan', 'kelurahan_id' => 1],
            ['nama' => 'Warungpring', 'kelurahan_id' => 1],
            ['nama' => 'Wonodoro', 'kelurahan_id' => 1],

            // Sidomulyo (id=2)
            ['nama' => 'Cangkring', 'kelurahan_id' => 2],
            ['nama' => 'Glodogan', 'kelurahan_id' => 2],
            ['nama' => 'Kuwon', 'kelurahan_id' => 2],
            ['nama' => 'Ngajaran', 'kelurahan_id' => 2],
            ['nama' => 'Ngireng-ireng', 'kelurahan_id' => 2],
            ['nama' => 'Palihan', 'kelurahan_id' => 2],
            ['nama' => 'Pinggir', 'kelurahan_id' => 2],
            ['nama' => 'Plebengan', 'kelurahan_id' => 2],
            ['nama' => 'Plematung', 'kelurahan_id' => 2],
            ['nama' => 'Ponggok', 'kelurahan_id' => 2],
            ['nama' => 'Prenggan', 'kelurahan_id' => 2],
            ['nama' => 'Selo', 'kelurahan_id' => 2],
            ['nama' => 'Sirat', 'kelurahan_id' => 2],
            ['nama' => 'Tempel', 'kelurahan_id' => 2],
            ['nama' => 'Turi', 'kelurahan_id' => 2],

            // Sumbermulyo (id=3)
            ['nama' => 'Bondalem', 'kelurahan_id' => 3],
            ['nama' => 'Caben', 'kelurahan_id' => 3],
            ['nama' => 'Cepoko', 'kelurahan_id' => 3],
            ['nama' => 'Gedongan', 'kelurahan_id' => 3],
            ['nama' => 'Gersik', 'kelurahan_id' => 3],
            ['nama' => 'Gunungan', 'kelurahan_id' => 3],
            ['nama' => 'Jogodayoh', 'kelurahan_id' => 3],
            ['nama' => 'Kaligondang', 'kelurahan_id' => 3],
            ['nama' => 'Kanutan', 'kelurahan_id' => 3],
            ['nama' => 'Kedon', 'kelurahan_id' => 3],
            ['nama' => 'Kintelan', 'kelurahan_id' => 3],
            ['nama' => 'Kutu', 'kelurahan_id' => 3],
            ['nama' => 'Plumbungan', 'kelurahan_id' => 3],
            ['nama' => 'Samen', 'kelurahan_id' => 3],
            ['nama' => 'Siten', 'kelurahan_id' => 3],
            ['nama' => 'Tangkilan', 'kelurahan_id' => 3],

            // KAPANEWON BANGUNTAPAN
            // Banguntapan (id=4)
            ['nama' => 'Jaranan', 'kelurahan_id' => 4],
            ['nama' => 'Jomblangan', 'kelurahan_id' => 4],
            ['nama' => 'Karangjambe', 'kelurahan_id' => 4],
            ['nama' => 'Modalan', 'kelurahan_id' => 4],
            ['nama' => 'Pelemwulung', 'kelurahan_id' => 4],
            ['nama' => 'Plumbon', 'kelurahan_id' => 4],
            ['nama' => 'Pringgolayan', 'kelurahan_id' => 4],
            ['nama' => 'Sorowajan', 'kelurahan_id' => 4],
            ['nama' => 'Tegal Tandan', 'kelurahan_id' => 4],
            ['nama' => 'Wonocatur', 'kelurahan_id' => 4],

            // Baturetno (id=5)
            ['nama' => 'Giang', 'kelurahan_id' => 5],
            ['nama' => 'Kalangan', 'kelurahan_id' => 5],
            ['nama' => 'Manggisan', 'kelurahan_id' => 5],
            ['nama' => 'Mantup', 'kelurahan_id' => 5],
            ['nama' => 'Ngipik', 'kelurahan_id' => 5],
            ['nama' => 'Pelem', 'kelurahan_id' => 5],
            ['nama' => 'Plakaran', 'kelurahan_id' => 5],
            ['nama' => 'Wiyoro', 'kelurahan_id' => 5],

            // Jagalan (id=6)
            ['nama' => 'Bodon', 'kelurahan_id' => 6],
            ['nama' => 'Sayangan', 'kelurahan_id' => 6],

            // Jambidan (id=7)
            ['nama' => 'Bintaran', 'kelurahan_id' => 7],
            ['nama' => 'Combongan', 'kelurahan_id' => 7],
            ['nama' => 'Dhuku', 'kelurahan_id' => 7],
            ['nama' => 'Joho', 'kelurahan_id' => 7],
            ['nama' => 'Kretek', 'kelurahan_id' => 7],
            ['nama' => 'Pamotan', 'kelurahan_id' => 7],
            ['nama' => 'Ponegaran', 'kelurahan_id' => 7],

            // Potorono (id=8)
            ['nama' => 'Balong Lor', 'kelurahan_id' => 8],
            ['nama' => 'Banjardadap', 'kelurahan_id' => 8],
            ['nama' => 'Condrowangsan', 'kelurahan_id' => 8],
            ['nama' => 'Mertosanan Kulon', 'kelurahan_id' => 8],
            ['nama' => 'Mertosanan Wetan', 'kelurahan_id' => 8],
            ['nama' => 'Nglaren', 'kelurahan_id' => 8],
            ['nama' => 'Potorono', 'kelurahan_id' => 8],
            ['nama' => 'Prangwedanan', 'kelurahan_id' => 8],
            ['nama' => 'Salakan', 'kelurahan_id' => 8],

            // Singosaren (id=9)
            ['nama' => 'Singosaren I', 'kelurahan_id' => 9],
            ['nama' => 'Singosaren II', 'kelurahan_id' => 9],
            ['nama' => 'Singosaren III', 'kelurahan_id' => 9],

            // Tamanan (id=10)
            ['nama' => 'Glagah Kidul', 'kelurahan_id' => 10],
            ['nama' => 'Glagah Lor', 'kelurahan_id' => 10],
            ['nama' => 'Grojogan', 'kelurahan_id' => 10],
            ['nama' => 'Kauman', 'kelurahan_id' => 10],
            ['nama' => 'Kragilan', 'kelurahan_id' => 10],
            ['nama' => 'Krobokan', 'kelurahan_id' => 10],
            ['nama' => 'Nglebeng', 'kelurahan_id' => 10],
            ['nama' => 'Sokowaten', 'kelurahan_id' => 10],
            ['nama' => 'Tamanan', 'kelurahan_id' => 10],

            // Wirokerten (id=11)
            ['nama' => 'Botokenceng', 'kelurahan_id' => 11],
            ['nama' => 'Glondong', 'kelurahan_id' => 11],
            ['nama' => 'Grojogan', 'kelurahan_id' => 11],
            ['nama' => 'Kepuh Kulon', 'kelurahan_id' => 11],
            ['nama' => 'Kepuh Wetan', 'kelurahan_id' => 11],
            ['nama' => 'Mutihan', 'kelurahan_id' => 11],
            ['nama' => 'Sampangan', 'kelurahan_id' => 11],
            ['nama' => 'Tobratan', 'kelurahan_id' => 11],

            // KAPANEWON BANTUL
            // Bantul (id=12)
            ['nama' => 'Babadan', 'kelurahan_id' => 12],
            ['nama' => 'Badegan', 'kelurahan_id' => 12],
            ['nama' => 'Bintaran', 'kelurahan_id' => 12],
            ['nama' => 'Bantul Warung', 'kelurahan_id' => 12],
            ['nama' => 'Bejen', 'kelurahan_id' => 12],
            ['nama' => 'Gandekan', 'kelurahan_id' => 12],
            ['nama' => 'Geblag', 'kelurahan_id' => 12],
            ['nama' => 'Grujugan', 'kelurahan_id' => 12],
            ['nama' => 'Karanggayam', 'kelurahan_id' => 12],
            ['nama' => 'Kurahan', 'kelurahan_id' => 12],
            ['nama' => 'Nyangkringan', 'kelurahan_id' => 12],
            ['nama' => 'Serayu', 'kelurahan_id' => 12],
            ['nama' => 'Teruman', 'kelurahan_id' => 12],

            // Palbapang (id=13)
            ['nama' => 'Bolon', 'kelurahan_id' => 13],
            ['nama' => 'Dagaran', 'kelurahan_id' => 13],
            ['nama' => 'Kadirojo', 'kelurahan_id' => 13],
            ['nama' => 'Karangasem', 'kelurahan_id' => 13],
            ['nama' => 'Karasan', 'kelurahan_id' => 13],
            ['nama' => 'Ngringinan', 'kelurahan_id' => 13],
            ['nama' => 'Peni', 'kelurahan_id' => 13],
            ['nama' => 'Serut', 'kelurahan_id' => 13],
            ['nama' => 'Sumuran', 'kelurahan_id' => 13],
            ['nama' => 'Taskombang', 'kelurahan_id' => 13],

            // Ringinharjo (id=14)
            ['nama' => 'Bantul Karang', 'kelurahan_id' => 14],
            ['nama' => 'Deresan', 'kelurahan_id' => 14],
            ['nama' => 'Gemahan', 'kelurahan_id' => 14],
            ['nama' => 'Gumuk', 'kelurahan_id' => 14],
            ['nama' => 'Mandingan', 'kelurahan_id' => 14],
            ['nama' => 'Soropaten', 'kelurahan_id' => 14],

            // Sabdodadi (id=15)
            ['nama' => 'Dukuh', 'kelurahan_id' => 15],
            ['nama' => 'Kadibeso', 'kelurahan_id' => 15],
            ['nama' => 'Keyongan', 'kelurahan_id' => 15],
            ['nama' => 'Manding', 'kelurahan_id' => 15],
            ['nama' => 'Neco', 'kelurahan_id' => 15],

            // Trirenggo (id=16)
            ['nama' => 'Bakulan', 'kelurahan_id' => 16],
            ['nama' => 'Bantul Timur', 'kelurahan_id' => 16],
            ['nama' => 'Bogoran', 'kelurahan_id' => 16],
            ['nama' => 'Cepoko', 'kelurahan_id' => 16],
            ['nama' => 'Gandekan', 'kelurahan_id' => 16],
            ['nama' => 'Gedongan', 'kelurahan_id' => 16],
            ['nama' => 'Gempolan', 'kelurahan_id' => 16],
            ['nama' => 'Karangmojo', 'kelurahan_id' => 16],
            ['nama' => 'Klembon', 'kelurahan_id' => 16],
            ['nama' => 'Kweden', 'kelurahan_id' => 16],
            ['nama' => 'Manding', 'kelurahan_id' => 16],
            ['nama' => 'Nogosari', 'kelurahan_id' => 16],
            ['nama' => 'Pasutan', 'kelurahan_id' => 16],
            ['nama' => 'Pepe', 'kelurahan_id' => 16],
            ['nama' => 'Priyan', 'kelurahan_id' => 16],
            ['nama' => 'Sragan', 'kelurahan_id' => 16],
            ['nama' => 'Sumberbatikan', 'kelurahan_id' => 16],

            // KAPANEWON DLINGO
            // Dlingo (id=17)
            ['nama' => 'Dlingo I', 'kelurahan_id' => 17],
            ['nama' => 'Dlingo II', 'kelurahan_id' => 17],
            ['nama' => 'Karipan I', 'kelurahan_id' => 17],
            ['nama' => 'Karipan II', 'kelurahan_id' => 17],
            ['nama' => 'Kebosungu I', 'kelurahan_id' => 17],
            ['nama' => 'Kebosungu II', 'kelurahan_id' => 17],
            ['nama' => 'Pakis I', 'kelurahan_id' => 17],
            ['nama' => 'Pakis II', 'kelurahan_id' => 17],
            ['nama' => 'Pokoh I', 'kelurahan_id' => 17],
            ['nama' => 'Pokoh II', 'kelurahan_id' => 17],

            // Jatimulyo (id=18)
            ['nama' => 'Bandean', 'kelurahan_id' => 18],
            ['nama' => 'Dodogan', 'kelurahan_id' => 18],
            ['nama' => 'Gayam', 'kelurahan_id' => 18],
            ['nama' => 'Kedug Ayak', 'kelurahan_id' => 18],
            ['nama' => 'Loputih', 'kelurahan_id' => 18],
            ['nama' => 'Maladan', 'kelurahan_id' => 18],
            ['nama' => 'Rejosari', 'kelurahan_id' => 18],
            ['nama' => 'Semuten', 'kelurahan_id' => 18],
            ['nama' => 'Tegallawas', 'kelurahan_id' => 18],

            // Mangunan (id=19)
            ['nama' => 'Cempluk', 'kelurahan_id' => 19],
            ['nama' => 'Kanigoro', 'kelurahan_id' => 19],
            ['nama' => 'Kediwung', 'kelurahan_id' => 19],
            ['nama' => 'Lemahbang', 'kelurahan_id' => 19],
            ['nama' => 'Mangunan', 'kelurahan_id' => 19],
            ['nama' => 'Sukorame', 'kelurahan_id' => 19],

            // Muntuk (id=20)
            ['nama' => 'Banjarharjo I', 'kelurahan_id' => 20],
            ['nama' => 'Banjarharjo II', 'kelurahan_id' => 20],
            ['nama' => 'Gunung Cilik', 'kelurahan_id' => 20],
            ['nama' => 'Karangasem', 'kelurahan_id' => 20],
            ['nama' => 'Muntuk', 'kelurahan_id' => 20],
            ['nama' => 'Sanggrahan I', 'kelurahan_id' => 20],
            ['nama' => 'Sanggrahan II', 'kelurahan_id' => 20],
            ['nama' => 'Seropan I', 'kelurahan_id' => 20],
            ['nama' => 'Seropan II', 'kelurahan_id' => 20],
            ['nama' => 'Seropan III', 'kelurahan_id' => 20],
            ['nama' => 'Tangkil', 'kelurahan_id' => 20],

            // Temuwuh (id=21)
            ['nama' => 'Jambewangi', 'kelurahan_id' => 21],
            ['nama' => 'Jurug', 'kelurahan_id' => 21],
            ['nama' => 'Kapingan', 'kelurahan_id' => 21],
            ['nama' => 'Klepu', 'kelurahan_id' => 21],
            ['nama' => 'Lungguh', 'kelurahan_id' => 21],
            ['nama' => 'Ngalempangan', 'kelurahan_id' => 21],
            ['nama' => 'Ngunu', 'kelurahan_id' => 21],
            ['nama' => 'Salam', 'kelurahan_id' => 21],
            ['nama' => 'Tanjan', 'kelurahan_id' => 21],
            ['nama' => 'Tanjung', 'kelurahan_id' => 21],
            ['nama' => 'Tekik', 'kelurahan_id' => 21],
            ['nama' => 'Temuwuh', 'kelurahan_id' => 21],

            // Terong (id=22)
            ['nama' => 'Kebo Kuning', 'kelurahan_id' => 22],
            ['nama' => 'Ngenep', 'kelurahan_id' => 22],
            ['nama' => 'Pencitrejo', 'kelurahan_id' => 22],
            ['nama' => 'Rejosari', 'kelurahan_id' => 22],
            ['nama' => 'Saradan', 'kelurahan_id' => 22],
            ['nama' => 'Sendangsari', 'kelurahan_id' => 22],
            ['nama' => 'Terong I', 'kelurahan_id' => 22],
            ['nama' => 'Terong II', 'kelurahan_id' => 22],

            // KAPANEWON IMOGIRI
            // Girirejo (id=23)
            ['nama' => 'Banyusumurup', 'kelurahan_id' => 23],
            ['nama' => 'Dronco', 'kelurahan_id' => 23],
            ['nama' => 'Kradenan', 'kelurahan_id' => 23],
            ['nama' => 'Tegalrejo', 'kelurahan_id' => 23],

            // Imogiri (id=24)
            ['nama' => 'Dukuh', 'kelurahan_id' => 24],
            ['nama' => 'Imogiri', 'kelurahan_id' => 24],
            ['nama' => 'Kertan', 'kelurahan_id' => 24],
            ['nama' => 'Paduresan', 'kelurahan_id' => 24],

            // Karangtalun (id=25)
            ['nama' => 'Bandungan', 'kelurahan_id' => 25],
            ['nama' => 'Karangtalun', 'kelurahan_id' => 25],
            ['nama' => 'Salaman', 'kelurahan_id' => 25],
            ['nama' => 'Sareyan', 'kelurahan_id' => 25],
            ['nama' => 'Setran', 'kelurahan_id' => 25],

            // Karangtengah (id=26)
            ['nama' => 'Karang Tengah', 'kelurahan_id' => 26],
            ['nama' => 'Karangrejek', 'kelurahan_id' => 26],
            ['nama' => 'Kemasan', 'kelurahan_id' => 26],
            ['nama' => 'Mojolegi', 'kelurahan_id' => 26],
            ['nama' => 'Numpukan', 'kelurahan_id' => 26],
            ['nama' => 'Pucung Rowong', 'kelurahan_id' => 26],

            // Kebonagung (id=27)
            ['nama' => 'Jayan', 'kelurahan_id' => 27],
            ['nama' => 'Kalangan', 'kelurahan_id' => 27],
            ['nama' => 'Kanten', 'kelurahan_id' => 27],
            ['nama' => 'Mandingan', 'kelurahan_id' => 27],
            ['nama' => 'Tlogo', 'kelurahan_id' => 27],

            // KAPANEWON JETIS
            // Canden (id=28)
            ['nama' => 'Banyudono', 'kelurahan_id' => 28],
            ['nama' => 'Beran', 'kelurahan_id' => 28],
            ['nama' => 'Canden', 'kelurahan_id' => 28],
            ['nama' => 'Gadungan Kepuh', 'kelurahan_id' => 28],
            ['nama' => 'Gadungan Pasar', 'kelurahan_id' => 28],
            ['nama' => 'Gaten', 'kelurahan_id' => 28],
            ['nama' => 'Jayan', 'kelurahan_id' => 28],
            ['nama' => 'Kategan', 'kelurahan_id' => 28],
            ['nama' => 'Kiringan', 'kelurahan_id' => 28],
            ['nama' => 'Kralas', 'kelurahan_id' => 28],
            ['nama' => 'Ngibikan', 'kelurahan_id' => 28],
            ['nama' => 'Plembutan', 'kelurahan_id' => 28],
            ['nama' => 'Pulo Kadang', 'kelurahan_id' => 28],
            ['nama' => 'Suren Kulon', 'kelurahan_id' => 28],
            ['nama' => 'Suren Wetan', 'kelurahan_id' => 28],
            ['nama' => 'Wonolopo', 'kelurahan_id' => 28],

            // Patalan (id=29)
            ['nama' => 'Bakulan Kulon', 'kelurahan_id' => 29],
            ['nama' => 'Bakulan Wetan', 'kelurahan_id' => 29],
            ['nama' => 'Bobok', 'kelurahan_id' => 29],
            ['nama' => 'Boto', 'kelurahan_id' => 29],
            ['nama' => 'Butuh', 'kelurahan_id' => 29],
            ['nama' => 'Dukuh Sukun', 'kelurahan_id' => 29],
            ['nama' => 'Gaduh', 'kelurahan_id' => 29],
            ['nama' => 'Gerselo', 'kelurahan_id' => 29],
            ['nama' => 'Jetis', 'kelurahan_id' => 29],
            ['nama' => 'Karangasem', 'kelurahan_id' => 29],
            ['nama' => 'Ketandan', 'kelurahan_id' => 29],
            ['nama' => 'Ngaglik', 'kelurahan_id' => 29],
            ['nama' => 'Panjang Jiwo', 'kelurahan_id' => 29],
            ['nama' => 'Patalan', 'kelurahan_id' => 29],
            ['nama' => 'Sulang Kidul', 'kelurahan_id' => 29],
            ['nama' => 'Sulang Lor', 'kelurahan_id' => 29],
            ['nama' => 'Tanjung Karang', 'kelurahan_id' => 29],
            ['nama' => 'Tanjung Lor', 'kelurahan_id' => 29],

            // Sumberagung (id=30)
            ['nama' => 'Balakan', 'kelurahan_id' => 30],
            ['nama' => 'Barongan', 'kelurahan_id' => 30],
            ['nama' => 'Beji', 'kelurahan_id' => 30],
            ['nama' => 'Bulus Kulon', 'kelurahan_id' => 30],
            ['nama' => 'Bungas', 'kelurahan_id' => 30],
            ['nama' => 'Cangkring', 'kelurahan_id' => 30],
            ['nama' => 'Kertan', 'kelurahan_id' => 30],
            ['nama' => 'Kiyaran', 'kelurahan_id' => 30],
            ['nama' => 'Manggung', 'kelurahan_id' => 30],
            ['nama' => 'Ngentak', 'kelurahan_id' => 30],
            ['nama' => 'Pangkah', 'kelurahan_id' => 30],
            ['nama' => 'Paten', 'kelurahan_id' => 30],
            ['nama' => 'Sawahan', 'kelurahan_id' => 30],
            ['nama' => 'Titang', 'kelurahan_id' => 30],
            ['nama' => 'Turi', 'kelurahan_id' => 30],

            // Trimulyo (id=31)
            ['nama' => 'Bembem', 'kelurahan_id' => 31],
            ['nama' => 'Blawong I', 'kelurahan_id' => 31],
            ['nama' => 'Blawong II', 'kelurahan_id' => 31],
            ['nama' => 'Bulu', 'kelurahan_id' => 31],
            ['nama' => 'Cembing', 'kelurahan_id' => 31],
            ['nama' => 'Denokan', 'kelurahan_id' => 31],
            ['nama' => 'Karang Semut', 'kelurahan_id' => 31],
            ['nama' => 'Kembang Songo', 'kelurahan_id' => 31],
            ['nama' => 'Ponggok I', 'kelurahan_id' => 31],
            ['nama' => 'Ponggok II', 'kelurahan_id' => 31],
            ['nama' => 'Puton', 'kelurahan_id' => 31],
            ['nama' => 'Sindet', 'kelurahan_id' => 31],

            // KAPANEWON KASIHAN
            // Bangunjiwo (id=32)
            ['nama' => 'Bangen', 'kelurahan_id' => 32],
            ['nama' => 'Bibis', 'kelurahan_id' => 32],
            ['nama' => 'Donotirto', 'kelurahan_id' => 32],
            ['nama' => 'Gedongan', 'kelurahan_id' => 32],
            ['nama' => 'Gendeng', 'kelurahan_id' => 32],
            ['nama' => 'Jipangan', 'kelurahan_id' => 32],
            ['nama' => 'Kalangan', 'kelurahan_id' => 32],
            ['nama' => 'Kalipucang', 'kelurahan_id' => 32],
            ['nama' => 'Kalirandu', 'kelurahan_id' => 32],
            ['nama' => 'Kasongan', 'kelurahan_id' => 32],
            ['nama' => 'Kenalan', 'kelurahan_id' => 32],
            ['nama' => 'Lemahdadi', 'kelurahan_id' => 32],
            ['nama' => 'Ngentak', 'kelurahan_id' => 32],
            ['nama' => 'Petung', 'kelurahan_id' => 32],
            ['nama' => 'Salakan', 'kelurahan_id' => 32],
            ['nama' => 'Sambikerep', 'kelurahan_id' => 32],
            ['nama' => 'Sembungan', 'kelurahan_id' => 32],
            ['nama' => 'Sribitan', 'kelurahan_id' => 32],
            ['nama' => 'Tirto', 'kelurahan_id' => 32],

            // Ngestiharjo (id=33)
            ['nama' => 'Cungkuk', 'kelurahan_id' => 33],
            ['nama' => 'Janten', 'kelurahan_id' => 33],
            ['nama' => 'Jomegatan', 'kelurahan_id' => 33],
            ['nama' => 'Kadipiro', 'kelurahan_id' => 33],
            ['nama' => 'Onggobayan', 'kelurahan_id' => 33],
            ['nama' => 'Sidorejo', 'kelurahan_id' => 33],
            ['nama' => 'Sonopakis Kidul', 'kelurahan_id' => 33],
            ['nama' => 'Sonopakis Lor', 'kelurahan_id' => 33],
            ['nama' => 'Sonosewu', 'kelurahan_id' => 33],
            ['nama' => 'Soragan', 'kelurahan_id' => 33],
            ['nama' => 'Sumberan', 'kelurahan_id' => 33],
            ['nama' => 'Tambak', 'kelurahan_id' => 33],

            // Tamantirto (id=34)
            ['nama' => 'Brajan', 'kelurahan_id' => 34],
            ['nama' => 'Gatak', 'kelurahan_id' => 34],
            ['nama' => 'Geblagan', 'kelurahan_id' => 34],
            ['nama' => 'Gonjen', 'kelurahan_id' => 34],
            ['nama' => 'Jadan', 'kelurahan_id' => 34],
            ['nama' => 'Jetis', 'kelurahan_id' => 34],
            ['nama' => 'Kasihan', 'kelurahan_id' => 34],
            ['nama' => 'Kembaran', 'kelurahan_id' => 34],
            ['nama' => 'Ngebel', 'kelurahan_id' => 34],
            ['nama' => 'Ngrame', 'kelurahan_id' => 34],

            // Tirtonirmolo (id=35)
            ['nama' => 'Beton', 'kelurahan_id' => 35],
            ['nama' => 'Dongkelan', 'kelurahan_id' => 35],
            ['nama' => 'Glondong', 'kelurahan_id' => 35],
            ['nama' => 'Jeblog', 'kelurahan_id' => 35],
            ['nama' => 'Jogonalan Kidul', 'kelurahan_id' => 35],
            ['nama' => 'Jogonalan Lor', 'kelurahan_id' => 35],
            ['nama' => 'Kalipakis', 'kelurahan_id' => 35],
            ['nama' => 'Kersan', 'kelurahan_id' => 35],
            ['nama' => 'Mrisi', 'kelurahan_id' => 35],
            ['nama' => 'Padokan Kidul', 'kelurahan_id' => 35],
            ['nama' => 'Padokan Lor', 'kelurahan_id' => 35],
            ['nama' => 'Plurugan', 'kelurahan_id' => 35],

            // KAPANEWON KRETEK
            // Donotirto (id=36)
            ['nama' => 'Busuran', 'kelurahan_id' => 36],
            ['nama' => 'Colo', 'kelurahan_id' => 36],
            ['nama' => 'Gading Daton', 'kelurahan_id' => 36],
            ['nama' => 'Gading Lumbung', 'kelurahan_id' => 36],
            ['nama' => 'Gadingharjo', 'kelurahan_id' => 36],
            ['nama' => 'Greges', 'kelurahan_id' => 36],
            ['nama' => 'Kalipakel', 'kelurahan_id' => 36],
            ['nama' => 'Mersan', 'kelurahan_id' => 36],
            ['nama' => 'Metuk', 'kelurahan_id' => 36],
            ['nama' => 'Mriyan', 'kelurahan_id' => 36],
            ['nama' => 'Palangjiwan', 'kelurahan_id' => 36],
            ['nama' => 'Sruwuh', 'kelurahan_id' => 36],
            ['nama' => 'Tegalsari', 'kelurahan_id' => 36],

            // Parangtritis (id=37)
            ['nama' => 'Bungkis', 'kelurahan_id' => 37],
            ['nama' => 'Depok', 'kelurahan_id' => 37],
            ['nama' => 'Duwuran', 'kelurahan_id' => 37],
            ['nama' => 'Grogol IX', 'kelurahan_id' => 37],
            ['nama' => 'Grogol VII', 'kelurahan_id' => 37],
            ['nama' => 'Grogol VIII', 'kelurahan_id' => 37],
            ['nama' => 'Grogol X', 'kelurahan_id' => 37],
            ['nama' => 'Kretek', 'kelurahan_id' => 37],
            ['nama' => 'Mancingan', 'kelurahan_id' => 37],
            ['nama' => 'Samiran', 'kelurahan_id' => 37],
            ['nama' => 'Sono', 'kelurahan_id' => 37],

            // Tirtohargo (id=38)
            ['nama' => 'Baros', 'kelurahan_id' => 38],
            ['nama' => 'Gegunung', 'kelurahan_id' => 38],
            ['nama' => 'Gunung Kunci', 'kelurahan_id' => 38],
            ['nama' => 'Kalangan', 'kelurahan_id' => 38],
            ['nama' => 'Karang', 'kelurahan_id' => 38],
            ['nama' => 'Muneng', 'kelurahan_id' => 38],

            // Tirtomulyo (id=39)
            ['nama' => 'Bracan', 'kelurahan_id' => 39],
            ['nama' => 'Gaten', 'kelurahan_id' => 39],
            ['nama' => 'Genting', 'kelurahan_id' => 39],
            ['nama' => 'Gondangan', 'kelurahan_id' => 39],
            ['nama' => 'Jebugan', 'kelurahan_id' => 39],
            ['nama' => 'Jetis', 'kelurahan_id' => 39],
            ['nama' => 'Karangweru', 'kelurahan_id' => 39],
            ['nama' => 'Karen', 'kelurahan_id' => 39],
            ['nama' => 'Kergan', 'kelurahan_id' => 39],
            ['nama' => 'Paliyan', 'kelurahan_id' => 39],
            ['nama' => 'Plesan', 'kelurahan_id' => 39],
            ['nama' => 'Punduhan', 'kelurahan_id' => 39],
            ['nama' => 'Soropadan', 'kelurahan_id' => 39],
            ['nama' => 'Tluren', 'kelurahan_id' => 39],
            ['nama' => 'Tokolan', 'kelurahan_id' => 39],

            // Tirtosari (id=40)
            ['nama' => 'Buruhan', 'kelurahan_id' => 40],
            ['nama' => 'Cimpon', 'kelurahan_id' => 40],
            ['nama' => 'Galan', 'kelurahan_id' => 40],
            ['nama' => 'Gelangan', 'kelurahan_id' => 40],
            ['nama' => 'Mulekan I', 'kelurahan_id' => 40],
            ['nama' => 'Mulekan II', 'kelurahan_id' => 40],
            ['nama' => 'Pangkah', 'kelurahan_id' => 40],
            ['nama' => 'Tegaltapen', 'kelurahan_id' => 40],

            // KAPANEWON PAJANGAN
            // Guwosari (id=41)
            ['nama' => 'Bungsing', 'kelurahan_id' => 41],
            ['nama' => 'Dukuh', 'kelurahan_id' => 41],
            ['nama' => 'Gandekan', 'kelurahan_id' => 41],
            ['nama' => 'Iroyudan', 'kelurahan_id' => 41],
            ['nama' => 'Kadisono', 'kelurahan_id' => 41],
            ['nama' => 'Kalakijo', 'kelurahan_id' => 41],
            ['nama' => 'Karangber', 'kelurahan_id' => 41],
            ['nama' => 'Kedung', 'kelurahan_id' => 41],
            ['nama' => 'Kembang Gede', 'kelurahan_id' => 41],
            ['nama' => 'Kembang Putihan', 'kelurahan_id' => 41],
            ['nama' => 'Kentholan Kidul', 'kelurahan_id' => 41],
            ['nama' => 'Kentholan Lor', 'kelurahan_id' => 41],
            ['nama' => 'Pring Gading', 'kelurahan_id' => 41],
            ['nama' => 'Santan', 'kelurahan_id' => 41],
            ['nama' => 'Watu Gedog', 'kelurahan_id' => 41],

            // Sendangsari (id=42)
            ['nama' => 'Beji Kulon', 'kelurahan_id' => 42],
            ['nama' => 'Beji Wetan', 'kelurahan_id' => 42],
            ['nama' => 'Benyo', 'kelurahan_id' => 42],
            ['nama' => 'Dadapbong', 'kelurahan_id' => 42],
            ['nama' => 'Gupakwarak', 'kelurahan_id' => 42],
            ['nama' => 'Jaten', 'kelurahan_id' => 42],
            ['nama' => 'Jetis', 'kelurahan_id' => 42],
            ['nama' => 'Kabrokan Kulon', 'kelurahan_id' => 42],
            ['nama' => 'Kabrokan Wetan', 'kelurahan_id' => 42],
            ['nama' => 'Kamijoro', 'kelurahan_id' => 42],
            ['nama' => 'Kayen', 'kelurahan_id' => 42],
            ['nama' => 'Krebet', 'kelurahan_id' => 42],
            ['nama' => 'Kunden', 'kelurahan_id' => 42],
            ['nama' => 'Mangir Kidul', 'kelurahan_id' => 42],
            ['nama' => 'Mangir Lor', 'kelurahan_id' => 42],
            ['nama' => 'Mangir Tengah', 'kelurahan_id' => 42],
            ['nama' => 'Manukan', 'kelurahan_id' => 42],
            ['nama' => 'Panjangan', 'kelurahan_id' => 42],

            // Triwidadi (id=43)
            ['nama' => 'Blabak', 'kelurahan_id' => 43],
            ['nama' => 'Butuh Kidul', 'kelurahan_id' => 43],
            ['nama' => 'Butuh Lor', 'kelurahan_id' => 43],
            ['nama' => 'Gampeng', 'kelurahan_id' => 43],
            ['nama' => 'Guwo', 'kelurahan_id' => 43],
            ['nama' => 'Jambean', 'kelurahan_id' => 43],
            ['nama' => 'Jogonandan', 'kelurahan_id' => 43],
            ['nama' => 'Jojoran Kulon', 'kelurahan_id' => 43],
            ['nama' => 'Jojoran Wetan', 'kelurahan_id' => 43],
            ['nama' => 'Kadireso', 'kelurahan_id' => 43],
            ['nama' => 'Kalisoko', 'kelurahan_id' => 43],
            ['nama' => 'Kayuhan Kulon', 'kelurahan_id' => 43],
            ['nama' => 'Kayuhan Wetan', 'kelurahan_id' => 43],
            ['nama' => 'Kersan', 'kelurahan_id' => 43],
            ['nama' => 'Nanggul', 'kelurahan_id' => 43],
            ['nama' => 'Ngincep', 'kelurahan_id' => 43],
            ['nama' => 'Pajangan', 'kelurahan_id' => 43],
            ['nama' => 'Plambongan', 'kelurahan_id' => 43],
            ['nama' => 'Polaman', 'kelurahan_id' => 43],
            ['nama' => 'Sabrang Kidul', 'kelurahan_id' => 43],
            ['nama' => 'Trucuk', 'kelurahan_id' => 43],

            // KAPANEWON PANDAK
            // Caturharjo (id=44)
            ['nama' => 'Banyuurip', 'kelurahan_id' => 44],
            ['nama' => 'Bogem', 'kelurahan_id' => 44],
            ['nama' => 'Glagahan', 'kelurahan_id' => 44],
            ['nama' => 'Gluntung Kidul', 'kelurahan_id' => 44],
            ['nama' => 'Gluntung Lor', 'kelurahan_id' => 44],
            ['nama' => 'Gumulan', 'kelurahan_id' => 44],
            ['nama' => 'Korowelang', 'kelurahan_id' => 44],
            ['nama' => 'Krapakan', 'kelurahan_id' => 44],
            ['nama' => 'Kuroboyo', 'kelurahan_id' => 44],
            ['nama' => 'Samparan', 'kelurahan_id' => 44],
            ['nama' => 'Tegallayang 10', 'kelurahan_id' => 44],
            ['nama' => 'Tegallayang 9', 'kelurahan_id' => 44],
            ['nama' => 'Tegalsempu', 'kelurahan_id' => 44],
            ['nama' => 'Tunjungan', 'kelurahan_id' => 44],

            // Gilangharjo (id=45)
            ['nama' => 'Banjarwaru', 'kelurahan_id' => 45],
            ['nama' => 'Bongsren', 'kelurahan_id' => 45],
            ['nama' => 'Daleman', 'kelurahan_id' => 45],
            ['nama' => 'Depok', 'kelurahan_id' => 45],
            ['nama' => 'Gunting', 'kelurahan_id' => 45],
            ['nama' => 'Jodog', 'kelurahan_id' => 45],
            ['nama' => 'Jomboran', 'kelurahan_id' => 45],
            ['nama' => 'Kadekrowo', 'kelurahan_id' => 45],
            ['nama' => 'Kadisoro', 'kelurahan_id' => 45],
            ['nama' => 'Karangasem', 'kelurahan_id' => 45],
            ['nama' => 'Karanggede', 'kelurahan_id' => 45],
            ['nama' => 'Kauman', 'kelurahan_id' => 45],
            ['nama' => 'Krekah', 'kelurahan_id' => 45],
            ['nama' => 'Ngaran', 'kelurahan_id' => 45],
            ['nama' => 'Tegallurung', 'kelurahan_id' => 45],

            // Triharjo (id=46)
            ['nama' => 'Ciren', 'kelurahan_id' => 46],
            ['nama' => 'Gunturan', 'kelurahan_id' => 46],
            ['nama' => 'Jalakan', 'kelurahan_id' => 46],
            ['nama' => 'Jaten', 'kelurahan_id' => 46],
            ['nama' => 'Jigudan', 'kelurahan_id' => 46],
            ['nama' => 'Juwono', 'kelurahan_id' => 46],
            ['nama' => 'Ngabean', 'kelurahan_id' => 46],
            ['nama' => 'Ngalarang', 'kelurahan_id' => 46],
            ['nama' => 'Siangan', 'kelurahan_id' => 46],
            ['nama' => 'Tirto', 'kelurahan_id' => 46],

            // Wijirejo (id=47)
            ['nama' => 'Bajang', 'kelurahan_id' => 47],
            ['nama' => 'Gedongsari', 'kelurahan_id' => 47],
            ['nama' => 'Gesikan III', 'kelurahan_id' => 47],
            ['nama' => 'Gesikan IV', 'kelurahan_id' => 47],
            ['nama' => 'Kauman', 'kelurahan_id' => 47],
            ['nama' => 'Kwalangan', 'kelurahan_id' => 47],
            ['nama' => 'Ngeblak', 'kelurahan_id' => 47],
            ['nama' => 'Pandak', 'kelurahan_id' => 47],
            ['nama' => 'Pedak', 'kelurahan_id' => 47],

            // KAPANEWON PIYUNGAN
            // Sitimulyo (id=48)
            ['nama' => 'Babatan', 'kelurahan_id' => 48],
            ['nama' => 'Banyakan I', 'kelurahan_id' => 48],
            ['nama' => 'Banyakan II', 'kelurahan_id' => 48],
            ['nama' => 'Banyakan III', 'kelurahan_id' => 48],
            ['nama' => 'Cepokojajar', 'kelurahan_id' => 48],
            ['nama' => 'Karanganom', 'kelurahan_id' => 48],
            ['nama' => 'Karanggayam', 'kelurahan_id' => 48],
            ['nama' => 'Karangploso', 'kelurahan_id' => 48],
            ['nama' => 'Karangtengah', 'kelurahan_id' => 48],
            ['nama' => 'Kunden', 'kelurahan_id' => 48],
            ['nama' => 'Madugondo', 'kelurahan_id' => 48],
            ['nama' => 'Mojosari', 'kelurahan_id' => 48],
            ['nama' => 'Monggang', 'kelurahan_id' => 48],
            ['nama' => 'Ngablak', 'kelurahan_id' => 48],
            ['nama' => 'Ngampon', 'kelurahan_id' => 48],
            ['nama' => 'Nganyang', 'kelurahan_id' => 48],
            ['nama' => 'Nglengis', 'kelurahan_id' => 48],
            ['nama' => 'Padangan', 'kelurahan_id' => 48],
            ['nama' => 'Padergunung I', 'kelurahan_id' => 48],
            ['nama' => 'Padergunung II', 'kelurahan_id' => 48],
            ['nama' => 'Somokaton', 'kelurahan_id' => 48],

            // Srimartani (id=49)
            ['nama' => 'Bulusari', 'kelurahan_id' => 49],
            ['nama' => 'Daraman', 'kelurahan_id' => 49],
            ['nama' => 'Kembangsari', 'kelurahan_id' => 49],
            ['nama' => 'Kemloko', 'kelurahan_id' => 49],
            ['nama' => 'Kwasen', 'kelurahan_id' => 49],
            ['nama' => 'Mandungan', 'kelurahan_id' => 49],
            ['nama' => 'Mojosari', 'kelurahan_id' => 49],
            ['nama' => 'Munggur', 'kelurahan_id' => 49],
            ['nama' => 'Mutihan', 'kelurahan_id' => 49],
            ['nama' => 'Petir', 'kelurahan_id' => 49],
            ['nama' => 'Piyungan', 'kelurahan_id' => 49],
            ['nama' => 'Pos Piyungan', 'kelurahan_id' => 49],
            ['nama' => 'Rejosari', 'kelurahan_id' => 49],
            ['nama' => 'Sanansari', 'kelurahan_id' => 49],
            ['nama' => 'Umbulsari', 'kelurahan_id' => 49],
            ['nama' => 'Wanujoyo Kidul', 'kelurahan_id' => 49],
            ['nama' => 'Wanujoyo Lor', 'kelurahan_id' => 49],

            // Srimulyo (id=50)
            ['nama' => 'Bangkel', 'kelurahan_id' => 50],
            ['nama' => 'Bintaran Kulon', 'kelurahan_id' => 50],
            ['nama' => 'Bintaran Wetan', 'kelurahan_id' => 50],
            ['nama' => 'Cikal', 'kelurahan_id' => 50],
            ['nama' => 'Duwet Gentong', 'kelurahan_id' => 50],
            ['nama' => 'Jasem', 'kelurahan_id' => 50],
            ['nama' => 'Jolosutro', 'kelurahan_id' => 50],
            ['nama' => 'Jombor', 'kelurahan_id' => 50],
            ['nama' => 'Kabregan', 'kelurahan_id' => 50],
            ['nama' => 'Kaligatuk', 'kelurahan_id' => 50],
            ['nama' => 'Klenggotan', 'kelurahan_id' => 50],
            ['nama' => 'Kradenan', 'kelurahan_id' => 50],
            ['nama' => 'Ngelosari', 'kelurahan_id' => 50],
            ['nama' => 'Ngijo', 'kelurahan_id' => 50],
            ['nama' => 'Onggopatran', 'kelurahan_id' => 50],
            ['nama' => 'Padeyan', 'kelurahan_id' => 50],
            ['nama' => 'Payak Cilik', 'kelurahan_id' => 50],
            ['nama' => 'Payak Tengah', 'kelurahan_id' => 50],
            ['nama' => 'Payak Wetan', 'kelurahan_id' => 50],
            ['nama' => 'Plesedan', 'kelurahan_id' => 50],
            ['nama' => 'Sandeyan', 'kelurahan_id' => 50],

            // KAPANEWON PLERET
            // Bawuran (id=51)
            ['nama' => 'Bawuran I', 'kelurahan_id' => 51],
            ['nama' => 'Bawuran II', 'kelurahan_id' => 51],
            ['nama' => 'Jambon', 'kelurahan_id' => 51],
            ['nama' => 'Kedungpring', 'kelurahan_id' => 51],
            ['nama' => 'Sanan', 'kelurahan_id' => 51],
            ['nama' => 'Sentulrejo', 'kelurahan_id' => 51],
            ['nama' => 'Tegalrejo', 'kelurahan_id' => 51],

            // Pleret (id=52)
            ['nama' => 'Bedukan', 'kelurahan_id' => 52],
            ['nama' => 'Gunungan', 'kelurahan_id' => 52],
            ['nama' => 'Gunungkelir', 'kelurahan_id' => 52],
            ['nama' => 'Kanggotan', 'kelurahan_id' => 52],
            ['nama' => 'Karet', 'kelurahan_id' => 52],
            ['nama' => 'Kauman', 'kelurahan_id' => 52],
            ['nama' => 'Kedaton', 'kelurahan_id' => 52],
            ['nama' => 'Keputren', 'kelurahan_id' => 52],
            ['nama' => 'Kerto', 'kelurahan_id' => 52],
            ['nama' => 'Trayeman', 'kelurahan_id' => 52],

            // Segoroyoso (id=53)
            ['nama' => 'Dahromo I', 'kelurahan_id' => 53],
            ['nama' => 'Dahromo II', 'kelurahan_id' => 53],
            ['nama' => 'Jembangan', 'kelurahan_id' => 53],
            ['nama' => 'Karanggayam', 'kelurahan_id' => 53],
            ['nama' => 'Kloron', 'kelurahan_id' => 53],
            ['nama' => 'Segoroyoso I', 'kelurahan_id' => 53],
            ['nama' => 'Segoroyoso II', 'kelurahan_id' => 53],
            ['nama' => 'Srumbung', 'kelurahan_id' => 53],
            ['nama' => 'Trukan', 'kelurahan_id' => 53],

            // Wonokromo (id=54)
            ['nama' => 'Brajan', 'kelurahan_id' => 54],
            ['nama' => 'Demangan', 'kelurahan_id' => 54],
            ['nama' => 'Jati', 'kelurahan_id' => 54],
            ['nama' => 'Jejeran I', 'kelurahan_id' => 54],
            ['nama' => 'Jejeran II', 'kelurahan_id' => 54],
            ['nama' => 'Karanganom', 'kelurahan_id' => 54],
            ['nama' => 'Ketonggo', 'kelurahan_id' => 54],
            ['nama' => 'Pandes I', 'kelurahan_id' => 54],
            ['nama' => 'Pandes II', 'kelurahan_id' => 54],
            ['nama' => 'Sareyan', 'kelurahan_id' => 54],
            ['nama' => 'Wonokromo I', 'kelurahan_id' => 54],
            ['nama' => 'Wonokromo II', 'kelurahan_id' => 54],

            // Wonolelo (id=55)
            ['nama' => 'Bojong', 'kelurahan_id' => 55],
            ['nama' => 'Cegokan', 'kelurahan_id' => 55],
            ['nama' => 'Depok', 'kelurahan_id' => 55],
            ['nama' => 'Guyangan', 'kelurahan_id' => 55],
            ['nama' => 'Kedungrejo', 'kelurahan_id' => 55],
            ['nama' => 'Majasari', 'kelurahan_id' => 55],
            ['nama' => 'Ploso', 'kelurahan_id' => 55],
            ['nama' => 'Purworejo', 'kelurahan_id' => 55],

            // KAPANEWON PUNDONG
            // Panjangrejo (id=56)
            ['nama' => 'Badan', 'kelurahan_id' => 56],
            ['nama' => 'Gedangan', 'kelurahan_id' => 56],
            ['nama' => 'Gedong', 'kelurahan_id' => 56],
            ['nama' => 'Grudo', 'kelurahan_id' => 56],
            ['nama' => 'Gunung Puyuh', 'kelurahan_id' => 56],
            ['nama' => 'Jamprit', 'kelurahan_id' => 56],
            ['nama' => 'Jetis', 'kelurahan_id' => 56],
            ['nama' => 'Krapyak Kulon', 'kelurahan_id' => 56],
            ['nama' => 'Krapyak Wetan', 'kelurahan_id' => 56],
            ['nama' => 'Nglembu', 'kelurahan_id' => 56],
            ['nama' => 'Nglorong', 'kelurahan_id' => 56],
            ['nama' => 'Panjang', 'kelurahan_id' => 56],
            ['nama' => 'Semampir', 'kelurahan_id' => 56],
            ['nama' => 'Soronanggan', 'kelurahan_id' => 56],
            ['nama' => 'Tarungan', 'kelurahan_id' => 56],
            ['nama' => 'Watu', 'kelurahan_id' => 56],

            // Seloharjo (id=57)
            ['nama' => 'Biro', 'kelurahan_id' => 57],
            ['nama' => 'Blali', 'kelurahan_id' => 57],
            ['nama' => 'Bobok Tempel', 'kelurahan_id' => 57],
            ['nama' => 'Darmojurang', 'kelurahan_id' => 57],
            ['nama' => 'Dukuh', 'kelurahan_id' => 57],
            ['nama' => 'Geger', 'kelurahan_id' => 57],
            ['nama' => 'Jelapan', 'kelurahan_id' => 57],
            ['nama' => 'Kalinampu', 'kelurahan_id' => 57],
            ['nama' => 'Kalipakem', 'kelurahan_id' => 57],
            ['nama' => 'Karangasem', 'kelurahan_id' => 57],
            ['nama' => 'Nambangan', 'kelurahan_id' => 57],
            ['nama' => 'Ngentak', 'kelurahan_id' => 57],
            ['nama' => 'Ngreco', 'kelurahan_id' => 57],
            ['nama' => 'Pentunh', 'kelurahan_id' => 57],
            ['nama' => 'Poyahan', 'kelurahan_id' => 57],
            ['nama' => 'Soka', 'kelurahan_id' => 57],

            // Srihardono (id=58)
            ['nama' => 'Baran', 'kelurahan_id' => 58],
            ['nama' => 'Candi', 'kelurahan_id' => 58],
            ['nama' => 'Ganjuran', 'kelurahan_id' => 58],
            ['nama' => 'Gulon', 'kelurahan_id' => 58],
            ['nama' => 'Jonggrangan', 'kelurahan_id' => 58],
            ['nama' => 'Klisat', 'kelurahan_id' => 58],
            ['nama' => 'Monggang', 'kelurahan_id' => 58],
            ['nama' => 'Nangsri', 'kelurahan_id' => 58],
            ['nama' => 'Paten', 'kelurahan_id' => 58],
            ['nama' => 'Piring', 'kelurahan_id' => 58],
            ['nama' => 'Potrobayan', 'kelurahan_id' => 58],
            ['nama' => 'Pranti', 'kelurahan_id' => 58],
            ['nama' => 'Pundong', 'kelurahan_id' => 58],
            ['nama' => 'Sawahan', 'kelurahan_id' => 58],
            ['nama' => 'Seyegan', 'kelurahan_id' => 58],
            ['nama' => 'Tangkil', 'kelurahan_id' => 58],
            ['nama' => 'Tulung', 'kelurahan_id' => 58],

            // KAPANEWON SANDEN
            // Gadingharjo (id=59)
            ['nama' => 'Daleman', 'kelurahan_id' => 59],
            ['nama' => 'Kalimundu', 'kelurahan_id' => 59],
            ['nama' => 'Karanganyar', 'kelurahan_id' => 59],
            ['nama' => 'Merten', 'kelurahan_id' => 59],
            ['nama' => 'Ngujung', 'kelurahan_id' => 59],
            ['nama' => 'Pranti', 'kelurahan_id' => 59],

            // Gadingsari (id=60)
            ['nama' => 'Bongos I', 'kelurahan_id' => 60],
            ['nama' => 'Bongos II', 'kelurahan_id' => 60],
            ['nama' => 'Dayu', 'kelurahan_id' => 60],
            ['nama' => 'Demakan', 'kelurahan_id' => 60],
            ['nama' => 'Demangan', 'kelurahan_id' => 60],
            ['nama' => 'Kenteng', 'kelurahan_id' => 60],
            ['nama' => 'Mangunharjo', 'kelurahan_id' => 60],
            ['nama' => 'Ketalo', 'kelurahan_id' => 60],
            ['nama' => 'Klagaran', 'kelurahan_id' => 60],
            ['nama' => 'Klatak', 'kelurahan_id' => 60],
            ['nama' => 'Nampan', 'kelurahan_id' => 60],
            ['nama' => 'Nanggulan', 'kelurahan_id' => 60],
            ['nama' => 'Patihan', 'kelurahan_id' => 60],
            ['nama' => 'Soka', 'kelurahan_id' => 60],
            ['nama' => 'Sorobayan', 'kelurahan_id' => 60],
            ['nama' => 'Tegesan', 'kelurahan_id' => 60],
            ['nama' => 'Wonorejo I', 'kelurahan_id' => 60],
            ['nama' => 'Wonorejo II', 'kelurahan_id' => 60],
            ['nama' => 'Wonoroto', 'kelurahan_id' => 60],

            // Murtigading (id=61)
            ['nama' => 'Bongoskenthi', 'kelurahan_id' => 61],
            ['nama' => 'Dagan', 'kelurahan_id' => 61],
            ['nama' => 'Kranggan', 'kelurahan_id' => 61],
            ['nama' => 'Kurahan I', 'kelurahan_id' => 61],
            ['nama' => 'Kurahan II', 'kelurahan_id' => 61],
            ['nama' => 'Mayungan I', 'kelurahan_id' => 61],
            ['nama' => 'Mayungan II', 'kelurahan_id' => 61],
            ['nama' => 'Ngentak', 'kelurahan_id' => 61],
            ['nama' => 'Peciro', 'kelurahan_id' => 61],
            ['nama' => 'Piring I', 'kelurahan_id' => 61],
            ['nama' => 'Piring II', 'kelurahan_id' => 61],
            ['nama' => 'Pucang Anom I', 'kelurahan_id' => 61],
            ['nama' => 'Pucang Anom II', 'kelurahan_id' => 61],
            ['nama' => 'Pucang Anom III', 'kelurahan_id' => 61],
            ['nama' => 'Sanden', 'kelurahan_id' => 61],
            ['nama' => 'Sanggrahan', 'kelurahan_id' => 61],
            ['nama' => 'Trisigan I', 'kelurahan_id' => 61],
            ['nama' => 'Trisigan II', 'kelurahan_id' => 61],

            // Srigading (id=62)
            ['nama' => 'Bonggalan', 'kelurahan_id' => 62],
            ['nama' => 'Celep', 'kelurahan_id' => 62],
            ['nama' => 'Ceme', 'kelurahan_id' => 62],
            ['nama' => 'Cetan', 'kelurahan_id' => 62],
            ['nama' => 'Dengokan', 'kelurahan_id' => 62],
            ['nama' => 'Dodogan', 'kelurahan_id' => 62],
            ['nama' => 'Gokerten', 'kelurahan_id' => 62],
            ['nama' => 'Kalijurang', 'kelurahan_id' => 62],
            ['nama' => 'Malangan', 'kelurahan_id' => 62],
            ['nama' => 'Ngemplak', 'kelurahan_id' => 62],
            ['nama' => 'Ngepet', 'kelurahan_id' => 62],
            ['nama' => 'Ngunan-unan', 'kelurahan_id' => 62],
            ['nama' => 'Sangkeh', 'kelurahan_id' => 62],
            ['nama' => 'Sogesanden', 'kelurahan_id' => 62],
            ['nama' => 'Srabahan', 'kelurahan_id' => 62],
            ['nama' => 'Tegalrejo', 'kelurahan_id' => 62],
            ['nama' => 'Tinggen', 'kelurahan_id' => 62],
            ['nama' => 'Wirosutan', 'kelurahan_id' => 62],
            ['nama' => 'Wuluhadeg', 'kelurahan_id' => 62],

            // KAPANEWON SEDAYU
            // Argodadi (id=63)
            ['nama' => 'Bakal', 'kelurahan_id' => 63],
            ['nama' => 'Bakal Dukuh', 'kelurahan_id' => 63],
            ['nama' => 'Brongkol', 'kelurahan_id' => 63],
            ['nama' => 'Cawan', 'kelurahan_id' => 63],
            ['nama' => 'Demangan', 'kelurahan_id' => 63],
            ['nama' => 'Dingkikan', 'kelurahan_id' => 63],
            ['nama' => 'Dumpuh', 'kelurahan_id' => 63],
            ['nama' => 'Kadibeso', 'kelurahan_id' => 63],
            ['nama' => 'Ngepek', 'kelurahan_id' => 63],
            ['nama' => 'Selogedong', 'kelurahan_id' => 63],
            ['nama' => 'Sukohardjo', 'kelurahan_id' => 63],
            ['nama' => 'Sumberan', 'kelurahan_id' => 63],
            ['nama' => 'Sungapan', 'kelurahan_id' => 63],
            ['nama' => 'Sungapan Dukuh', 'kelurahan_id' => 63],

            // Argomulyo (id=64)
            ['nama' => 'Kaliberot', 'kelurahan_id' => 64],
            ['nama' => 'Kaliurang', 'kelurahan_id' => 64],
            ['nama' => 'Karanglo', 'kelurahan_id' => 64],
            ['nama' => 'Kemusuk Kidul', 'kelurahan_id' => 64],
            ['nama' => 'Kemusuk Lor', 'kelurahan_id' => 64],
            ['nama' => 'Panggang', 'kelurahan_id' => 64],
            ['nama' => 'Pedes', 'kelurahan_id' => 64],
            ['nama' => 'Plawonan', 'kelurahan_id' => 64],
            ['nama' => 'Puluhan', 'kelurahan_id' => 64],
            ['nama' => 'Samben', 'kelurahan_id' => 64],
            ['nama' => 'Sengon Karang', 'kelurahan_id' => 64],
            ['nama' => 'Srontakan', 'kelurahan_id' => 64],
            ['nama' => 'Surobayan', 'kelurahan_id' => 64],
            ['nama' => 'Watu', 'kelurahan_id' => 64],

            // Argorejo (id=65)
            ['nama' => 'Bandut Kidul', 'kelurahan_id' => 65],
            ['nama' => 'Bandut Lor', 'kelurahan_id' => 65],
            ['nama' => 'Gunungpolo', 'kelurahan_id' => 65],
            ['nama' => 'Kalakan', 'kelurahan_id' => 65],
            ['nama' => 'Kepuhan', 'kelurahan_id' => 65],
            ['nama' => 'Metes', 'kelurahan_id' => 65],
            ['nama' => 'Ngentak', 'kelurahan_id' => 65],
            ['nama' => 'Pendul', 'kelurahan_id' => 65],
            ['nama' => 'Pereng Weten', 'kelurahan_id' => 65],
            ['nama' => 'Polaman', 'kelurahan_id' => 65],
            ['nama' => 'Semampir', 'kelurahan_id' => 65],
            ['nama' => 'Senowo', 'kelurahan_id' => 65],
            ['nama' => 'Sundikidul', 'kelurahan_id' => 65],

            // Argosari (id=66)
            ['nama' => 'Botokan', 'kelurahan_id' => 66],
            ['nama' => 'Gayam', 'kelurahan_id' => 66],
            ['nama' => 'Gubug', 'kelurahan_id' => 66],
            ['nama' => 'Gunung Mojo', 'kelurahan_id' => 66],
            ['nama' => 'Jambon', 'kelurahan_id' => 66],
            ['nama' => 'Jaten', 'kelurahan_id' => 66],
            ['nama' => 'Jurug', 'kelurahan_id' => 66],
            ['nama' => 'Kalijoho', 'kelurahan_id' => 66],
            ['nama' => 'Klangen', 'kelurahan_id' => 66],
            ['nama' => 'Pedusan', 'kelurahan_id' => 66],
            ['nama' => 'Sedayu', 'kelurahan_id' => 66],
            ['nama' => 'Tapen', 'kelurahan_id' => 66],
            ['nama' => 'Tonalan', 'kelurahan_id' => 66],

            // KAPANEWON SEWON
            // Bangunharjo (id=67)
            ['nama' => 'Bakung', 'kelurahan_id' => 67],
            ['nama' => 'Demangan', 'kelurahan_id' => 67],
            ['nama' => 'Druwo', 'kelurahan_id' => 67],
            ['nama' => 'Gatak', 'kelurahan_id' => 67],
            ['nama' => 'Jotawang', 'kelurahan_id' => 67],
            ['nama' => 'Jurug', 'kelurahan_id' => 67],
            ['nama' => 'Mredo', 'kelurahan_id' => 67],
            ['nama' => 'Ngoto', 'kelurahan_id' => 67],
            ['nama' => 'Pandeyan', 'kelurahan_id' => 67],
            ['nama' => 'Randubelang', 'kelurahan_id' => 67],
            ['nama' => 'Salakan', 'kelurahan_id' => 67],
            ['nama' => 'Saman', 'kelurahan_id' => 67],
            ['nama' => 'Semail', 'kelurahan_id' => 67],
            ['nama' => 'Tanjung', 'kelurahan_id' => 67],
            ['nama' => 'Tarudan', 'kelurahan_id' => 67],
            ['nama' => 'Widoro', 'kelurahan_id' => 67],
            ['nama' => 'Wojo', 'kelurahan_id' => 67],

            // Panggungharjo (id=68)
            ['nama' => 'Cabean', 'kelurahan_id' => 68],
            ['nama' => 'Dongkelan', 'kelurahan_id' => 68],
            ['nama' => 'Garon', 'kelurahan_id' => 68],
            ['nama' => 'Geneng', 'kelurahan_id' => 68],
            ['nama' => 'Glondong', 'kelurahan_id' => 68],
            ['nama' => 'Glugo', 'kelurahan_id' => 68],
            ['nama' => 'Jaranan', 'kelurahan_id' => 68],
            ['nama' => 'Krapyak Kulon', 'kelurahan_id' => 68],
            ['nama' => 'Krapyak Wetan', 'kelurahan_id' => 68],
            ['nama' => 'Kweni', 'kelurahan_id' => 68],
            ['nama' => 'Ngireng-ireng', 'kelurahan_id' => 68],
            ['nama' => 'Pandes', 'kelurahan_id' => 68],
            ['nama' => 'Pelemsewu', 'kelurahan_id' => 68],
            ['nama' => 'Sawit', 'kelurahan_id' => 68],

            // Pendowoharjo (id=69)
            ['nama' => 'Bandung', 'kelurahan_id' => 69],
            ['nama' => 'Banyon', 'kelurahan_id' => 69],
            ['nama' => 'Blunyahan', 'kelurahan_id' => 69],
            ['nama' => 'Cepit', 'kelurahan_id' => 69],
            ['nama' => 'Dagen', 'kelurahan_id' => 69],
            ['nama' => 'Diro', 'kelurahan_id' => 69],
            ['nama' => 'Kaliputih', 'kelurahan_id' => 69],
            ['nama' => 'Krandohan', 'kelurahan_id' => 69],
            ['nama' => 'Miri', 'kelurahan_id' => 69],
            ['nama' => 'Monggang', 'kelurahan_id' => 69],
            ['nama' => 'Ngaglik', 'kelurahan_id' => 69],
            ['nama' => 'Ngimbang', 'kelurahan_id' => 69],
            ['nama' => 'Pendowo', 'kelurahan_id' => 69],
            ['nama' => 'Pucung', 'kelurahan_id' => 69],
            ['nama' => 'Rogoitan', 'kelurahan_id' => 69],
            ['nama' => 'Sawahan', 'kelurahan_id' => 69],

            // Timbulharjo (id=70)
            ['nama' => 'Balong', 'kelurahan_id' => 70],
            ['nama' => 'Bibis', 'kelurahan_id' => 70],
            ['nama' => 'Dadapan', 'kelurahan_id' => 70],
            ['nama' => 'Dagan', 'kelurahan_id' => 70],
            ['nama' => 'Dobalan', 'kelurahan_id' => 70],
            ['nama' => 'Gabusan', 'kelurahan_id' => 70],
            ['nama' => 'Gatak', 'kelurahan_id' => 70],
            ['nama' => 'Kepek', 'kelurahan_id' => 70],
            ['nama' => 'Kowen I', 'kelurahan_id' => 70],
            ['nama' => 'Kowen II', 'kelurahan_id' => 70],
            ['nama' => 'Mriyan', 'kelurahan_id' => 70],
            ['nama' => 'Ngasem', 'kelurahan_id' => 70],
            ['nama' => 'Ngentak', 'kelurahan_id' => 70],
            ['nama' => 'Sewon', 'kelurahan_id' => 70],
            ['nama' => 'Sudimoro', 'kelurahan_id' => 70],
            ['nama' => 'Tembi', 'kelurahan_id' => 70],

            // KAPANEWON SRANDAKAN
            // Poncosari (id=71)
            ['nama' => 'Babakan', 'kelurahan_id' => 71],
            ['nama' => 'Bayuran', 'kelurahan_id' => 71],
            ['nama' => 'Besole', 'kelurahan_id' => 71],
            ['nama' => 'Bibis', 'kelurahan_id' => 71],
            ['nama' => 'Bodowaluh', 'kelurahan_id' => 71],
            ['nama' => 'Cangkring', 'kelurahan_id' => 71],
            ['nama' => 'Godekan', 'kelurahan_id' => 71],
            ['nama' => 'Gunturgeni', 'kelurahan_id' => 71],
            ['nama' => 'Jopaten', 'kelurahan_id' => 71],
            ['nama' => 'Jragan I', 'kelurahan_id' => 71],
            ['nama' => 'Jragan II', 'kelurahan_id' => 71],
            ['nama' => 'Karang', 'kelurahan_id' => 71],
            ['nama' => 'Kokap', 'kelurahan_id' => 71], 
            ['nama' => 'Koripan', 'kelurahan_id' => 71],
            ['nama' => 'Krajan', 'kelurahan_id' => 71],
            ['nama' => 'Kuwaru', 'kelurahan_id' => 71],
            ['nama' => 'Ngentak', 'kelurahan_id' => 71],
            ['nama' => 'Polosiyo', 'kelurahan_id' => 71],
            ['nama' => 'Sambeng I', 'kelurahan_id' => 71],
            ['nama' => 'Sambeng II', 'kelurahan_id' => 71],
            ['nama' => 'Sambeng III', 'kelurahan_id' => 71],
            ['nama' => 'Singgelo', 'kelurahan_id' => 71],
            ['nama' => 'Talkondo', 'kelurahan_id' => 71],
            ['nama' => 'Wonotinggal', 'kelurahan_id' => 71],

            // Trimurti (id=72)
            ['nama' => 'Bendo', 'kelurahan_id' => 72],
            ['nama' => 'Cangunan', 'kelurahan_id' => 72],
            ['nama' => 'Celan', 'kelurahan_id' => 72],
            ['nama' => 'Greso', 'kelurahan_id' => 72],
            ['nama' => 'Gunung Saren Lor', 'kelurahan_id' => 72],
            ['nama' => 'Gunungsaren', 'kelurahan_id' => 72],
            ['nama' => 'Jetis', 'kelurahan_id' => 72],
            ['nama' => 'Lopati', 'kelurahan_id' => 72],
            ['nama' => 'Mangiran', 'kelurahan_id' => 72],
            ['nama' => 'Nengahan', 'kelurahan_id' => 72],
            ['nama' => 'Pedak', 'kelurahan_id' => 72],
            ['nama' => 'Prokerten', 'kelurahan_id' => 72],
            ['nama' => 'Puluhan Kidul', 'kelurahan_id' => 72],
            ['nama' => 'Puluhan Lor', 'kelurahan_id' => 72],
            ['nama' => 'Puron', 'kelurahan_id' => 72],
            ['nama' => 'Sapuangin', 'kelurahan_id' => 72],
            ['nama' => 'Sawahan', 'kelurahan_id' => 72],
            ['nama' => 'Srandakan', 'kelurahan_id' => 72],

        ];
        foreach ($data as $item) {
            Padukuhan::create($item);
        }
    }
}
